version: 0.0
os: linux
files:
  - source: / 
    destination: /home/ubuntu/iq4-web-staging
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 1000
      runas: root
  ApplicationStart:
    - location: scripts/stop_server
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
